version: "3.9"

services:
  tutorial_app:
    build: .
    container_name: tutorial_app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/tutorial_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
  psql-db:
    image: postgres
    container_name: psql-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tutorial_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: {}

